version: 0.2

phases:
  install:
    commands:
      - pwd
      - ls -alrt
      - . ./docker/codebuild-extras.sh
      - aws --version
      - printenv
      - echo "------ ${CODEBUILD_GIT_BRANCH} ------"
  build:
    commands:
      - mkdir -p docker/artifacts
      - cd docker && docker-compose build compile
      - cd docker && docker-compose up compile
  post_build:
    commands:
      - AWS_ACCESS_KEY_ID=foo AWS_SECRET_ACCESS_KEY=bar echo "ToDo - install to ECS..."

artifacts:
  files:
    - docker/artifacts/*.jar
  name: artifact-${CODEBUILD_GIT_BRANCH}-$(date +%Y-%m-%d_%H-%M-%S).zip

